### ISSUE TITLE
error bang

### ISSUE THREAD

**Issue by AKUN1-oss** [Tnodes/auto-get-sonic-faucet#1]
09:42:02 | INFO    | Making request to API with proxy...
09:42:03 | WARNING | Received 429 Too Many Requests, skipping to next wallet

**Comment by Tnodes** [comment]
Hai @AKUN1-oss, itu response dari API faucetnya emang seperti itu lebih baik tambah jumlah wallet aja semakin banyak semakin bagus.

**Comment by tamma12** [comment]
format proxy gimna yg benar?

**Comment by tamma12** [comment]
> Hai @AKUN1-oss, itu response dari API faucetnya emang seperti itu lebih baik tambah jumlah wallet aja semakin banyak semakin bagus.

format proxy yg benar gimna bang?

**Comment by Tnodes** [comment]
`http://username:password@ip:port`

**Comment by Tnodes** [comment]
Saya tutup issue ini jika ada issue baru silahkan buat new issue, terima kasih.
