### ISSUE TITLE
supprt for testnetv1

### ISSUE THREAD

**Issue by valgaz-za** [Tnodes/auto-get-sonic-faucet#3]
add testnet v1 sir

**Comment by Tnodes** [comment]
its working for testnet to

**Comment by unpredictablemahi** [comment]
For latest testnet frontier v1 released 2-5 days ago ...

**Comment by Tnodes** [comment]
Need at least 0.01 SOL in solana mainnet to request v1 faucet, i can't bypass without 0 balance in solana mainnet

**Comment by aybeckz** [comment]
do you have v1 api faucet url ?

**Comment by Tnodes** [comment]
> do you have v1 api faucet url ?

Yes, chat me in telegram. I will close this issue.

Thank you.
